version = 1

test_patterns = [
    "tests/**",
    "test_*.py"
]

exclude_patterns = [
    "**/__pycache__/",
    "yflive/yfquote_pb2.py",
    "yflive/yfquote.proto"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
