name: yflive

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - name: Chechout repo
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} environment
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -U pip setuptools wheel readme_renderer twine
          pip install -r requirements.txt
      - name: Build yflive
        run: |
          python -c "import setuptools; print('Setup tools version'); print(setuptools.__version__)"
          python setup.py sdist
          twine check dist/*
      - name: Run unittests
        run: |
          python -m unittest discover ./tests -p "test_*.py"
        env:
          TEST_WITH_INTERNET: 1
